In [7]:
import numpy as np

def is_numerical_array(array: np.ndarray):
    """
    Checks if the input is a numerical NumPy array.

    Parameters:
    array (np.ndarray): The array to check.

    Returns:
    bool: True if the array is a numerical NumPy array, False otherwise.
    """
    return isinstance(array, np.ndarray) and np.issubdtype(array.dtype, np.number)


def is_3d_numpy_vector(vector: np.ndarray):
    """
    Checks if the input is a 3-dimensional numerical vector represented as a NumPy array.

    Parameters:
    vector (np.ndarray): The vector to check.

    Returns:
    bool: True if the vector is a 3-dimensional NumPy array, False otherwise.
    """
    return is_numerical_array(vector) and vector.ndim == 1 and vector.shape[0] == 3

def validate_3d_numpy_vector(vector:np.ndarray):
    """
    Validates that the input is a 3-dimensional vector represented as a NumPy array.

    Parameters:
    vector (np.ndarray): The vector to validate.

    Raises:
    ValueError: If the input is not a 3-dimensional NumPy array.
    """
    if not is_3d_numpy_vector(vector):
        raise ValueError((
            "Input is not a 3-dimensional numpy vector ",
            f"Current shape: {vector.shape}" if isinstance(vector, np.ndarray) \
            else f"Current type: {type(vector)}"))

def is_3d_numpy_numeric_vector(vector: np.ndarray):
    """
    Checks if the input is a 3-dimensional numeric vector represented as a NumPy array.

    Parameters:
    vector (np.ndarray): The vector to check.

    Returns:
    bool: True if the vector is a 3-dimensional numeric NumPy array, False otherwise.
    """
    return is_3d_numpy_vector(vector) and np.issubdtype(vector.dtype, np.number)

In [12]:
import numpy as np
import time

def is_3d_vector(vector):
    """
    Checks if the input is a 3-dimensional vector represented as a NumPy array.

    Parameters:
    vector (np.ndarray): The vector to check.

    Returns:
    bool: True if the vector is a 3-dimensional NumPy array, False otherwise.
    """
    return isinstance(vector, np.ndarray) and vector.ndim == 1 and vector.shape[0] == 3

def evaluate_cpu_time(func, *args, iterations=1000000):
    """
    Evaluates the CPU time of a function.

    Parameters:
    func (callable): The function to evaluate.
    *args: Arguments to pass to the function.
    iterations (int): Number of times to run the function.

    Returns:
    float: The average CPU time per function call in seconds.
    """
    start_time = time.process_time()
    for _ in range(iterations):
        func(*args)
    end_time = time.process_time()
    return (end_time - start_time) / iterations

# Example vectors
v1 = np.array([1, 2, 3])
v2 = np.array([[1, 2, 3]])
v3 = np.array([1, 2, 3, 4])

# Evaluating CPU time
avg_time_v1 = evaluate_cpu_time(is_3d_vector, v1)
avg_time_v2 = evaluate_cpu_time(is_3d_vector, v2)
avg_time_v3 = evaluate_cpu_time(is_3d_vector, v3)

print(f"Average CPU time for v1: {avg_time_v1:.10f} seconds")
print(f"Average CPU time for v2: {avg_time_v2:.10f} seconds")
print(f"Average CPU time for v3: {avg_time_v3:.10f} seconds")
tt = np.array([1, 2, "3"])
print(tt)


Average CPU time for v1: 0.0000001206 seconds
Average CPU time for v2: 0.0000000669 seconds
Average CPU time for v3: 0.0000000960 seconds
['1' '2' '3']


In [1]:
from yggdrasil.earth import earth_ellipsoid_model


a = earth_ellipsoid_model('titi')
print(a)

KeyError: "'titi' is not a valid ellipsoid model name. Available names are: WGS84, Spherical Earth"

In [13]:
import numpy as np
from numpy.typing import NDArray

def is_3x3_numerical_matrix(matrix: NDArray[np.float64]) -> bool:
    """
    Checks if the input is a 3x3 numerical matrix.

    Parameters:
        matrix (NDArray[np.float64]): The matrix to check.

    Returns:
        bool: True if the matrix is a 3x3 numerical matrix, False otherwise.
    """
    return isinstance(matrix, np.ndarray) and matrix.shape == (3, 3) and np.issubdtype(matrix.dtype, np.number)

# Example usage
valid_matrix = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
int_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Integer
invalid_matrix = np.array([[1.0, 2.0], [3.0, 4.0]])  # Not 3x3
non_numeric_matrix = np.array([["a", "b", "c"], ["d", "e", "f"], ["g", "h", "i"]])  # Non-numeric
print(is_3x3_numerical_matrix(valid_matrix))  # Should return True
print(is_3x3_numerical_matrix(invalid_matrix))  # Should return False
print(is_3x3_numerical_matrix(non_numeric_matrix))  # Should return False
print(is_3x3_numerical_matrix(int_matrix))  # Should return True


evaluate_cpu_time(is_3x3_numerical_matrix, valid_matrix)
# evaluate_cpu_time(is_3x3_numerical_matrix, invalid_matrix)
# evaluate_cpu_time(is_3x3_numerical_matrix, non_numeric_matrix)
# evaluate_cpu_time(is_3x3_numerical_matrix, int_matrix)


True
False
False
True


4.7603799999999996e-07

In [14]:
from typing import Annotated, Literal, TypeVar

import numpy as np

# Define a type variable for the data type
DType = TypeVar("DType", bound=np.generic)

# Create type aliases for arrays with specific shapes
Array4 = Annotated[np.typing.NDArray[DType], Literal[4]]
Array3x3 = Annotated[np.typing.NDArray[DType], Literal[3, 3]]
ArrayNxNx3 = Annotated[np.typing.NDArray[DType], Literal["N", "N", 3]]

# Example usage with type checking
def foo(arr: Array4[np.int32]) -> None:
  """
  Example function that expects an ndarray with shape (4,) and dtype int32

  Args:
      arr: The input ndarray
  """
  assert arr.shape == (4,)
  assert np.issubdtype(arr.dtype, np.int32)
  # Do something with the array

# Example usage
some_array = np.array([1, 2, 3, 4], dtype=np.int32)
foo(some_array)


TypeError: Too many arguments for numpy.ndarray[typing.Any, numpy.dtype[+_ScalarType_co]]; actual 2, expected 1

In [16]:
import numpy as np
from nptyping import NDArray, Float, Shape
from beartype import beartype

# Define a type alias for a 3x3 numerical matrix
Matrix3x3 = NDArray[Shape["3, 3"], Float]

# Example function using the type hint
def create_3x3_matrix() -> Matrix3x3:
    """
    Creates and returns a 3x3 numerical matrix.

    Returns:
        Matrix3x3: A 3x3 numerical matrix.
    """
    matrix: Matrix3x3 = np.array([[1.0, 2.0, 3.0],
                                  [4.0, 5.0, 6.0],
                                  [7.0, 8.0, 9.0]], dtype=np.float64)
    return matrix

# Example usage
matrix = create_3x3_matrix()
print(matrix)

# Validate the type and shape of the matrix
assert matrix.shape == (3, 3) and matrix.dtype == np.float64

@beartype
def test_fct(matrix: Matrix3x3) -> None:
    print("Ok everything is fine")


test_fct(matrix)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


BeartypeDecorHintPep604Exception: Type hint NDArray[Shape['3, 3'], Float] inconsistent with respect to repr() strings. Since @beartype requires consistency between type hints and repr() strings, this hint is unsupported by @beartype. Consider reporting this issue to the third-party developer implementing this hint: e.g.,
	>>> repr(NDArray[Shape['3, 3'], Float])
	NDArray[Shape['3, 3'], Float]  # <-- this is fine
	>>> repr(NDArray[Shape['3, 3'], Float] | int)
	nptyping.ndarray.NDArray | int  # <-- *THIS IS REALLY SUPER BAD*

	# Ideally, that output should instead resemble:
	>>> repr(NDArray[Shape['3, 3'], Float] | int)
	NDArray[Shape['3, 3'], Float] | int  # <-- what @beartype wants!